# tab_stop_width 4

# vim:fileencoding=utf-8:foldmethod=marker

font_family      "JetBrainsMono Nerd Font Mono"

enable_audio_bell no

tab_bar_edge top

# Rename the current tab
map ctrl+shift+s set_tab_title

# Changes the look (options: fade, slant, separator, powerline, custom, shell)
tab_bar_style powerline

# If using powerline, you can change the shape (slanted, angled, round)
tab_powerline_style slanted

# Toggle between the current and previous tab
map ctrl+tab goto_tab 0
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map ctrl+0 goto_tab 10

font_size 10.0

map ctrl+v paste_from_clipboard

 foreground #dddddd
 background #000000

#: The foreground and background colors.

 background_opacity 0.65

# Zoom in
map ctrl+equal  change_font_size all +1.0
map ctrl+plus   change_font_size all +1.0

# Zoom out
map ctrl+minus  change_font_size all -1.0

# Reset zoom (Ctrl+0)
map ctrl+shift+0      change_font_size all 0

# 1. Enable the 'splits' layout
enabled_layouts splits,stack,grid,tall


# Toggle a split to be full-screen and back (Like Tmux Zoom)
map ctrl+shift+z toggle_layout stack

# Move focus between splits using Ctrl+Shift + Arrows
# Move between splits (windows) using Alt + Arrow Keys
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

# BEGIN_KITTY_FONTS
# font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=FiraCodeNF-Reg
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
