[General]
__userfile__=true
iconTheme=
panels=panel1

[desktopswitch3]
alignment=Left
labelType=1
rows=1
showOnlyActive=false
type=desktopswitch

[fancymenu2]
alignment=Left
type=fancymenu

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=1
font-color=@Variant(\0\0\0\x43\x1\xff\xff\xd6\xd6\xd6\xd6\xd6\xd6\0\0)
hidable=false
hide-on-overlap=false
iconSize=10
lineCount=1
lockPanel=false
opacity=100
panelSize=19
plugins=fancymenu2, desktopswitch3
position=Bottom
reserve-space=true
show-delay=0
visible-margin=false
width=100
width-percent=true
