[ids]


# to get more ids run `keyd monitor`.
1a2c:2d23

# The laptop's keyboard itself.
0001:0001
1532:0065


[main]

capslock = leftcontrol
compose = leftalt

rightalt = overloadt(rightalt_shift, oneshot(rightalt_shift), 250)


# For my razer mouse
f24 = enter

# Just to fix compose
escape = overload(extend_escape, escape)


power = noop
wakeup = noop


[extend_escape]

# Cuz the compose key is not the compose key anymore in this config.
compose = compose

# For voxtype stt
space = scrolllock


# Screenshots stuff: Screenshtos, pinning screenshots. delayed screenshots.
# -----------------------------------------------------------------------------------
f2 = command(sudo -u dex -H /home/dex/scripts/dex_session_launcher.sh bash -c "FILE=/tmp/pin_\$(date +%s).png; scrot -s \$FILE && feh --class 'pin_shot' -. \$FILE &")
f1 = command(sudo -u dex /home/dex/scripts/f1_scrot.sh)
f3 = command(sudo -u dex -H /home/dex/scripts/dex_session_launcher.sh bash -c "WID=\$(xdotool getactivewindow); flameshot gui; xdotool windowfocus \$WID")
f4 = command(sudo -u dex /home/dex/scripts/f4_screenshot.sh)
f5 = command(sudo -u dex -H /home/dex/scripts/dex_session_launcher.sh flameshot gui -s --pin)


# Thunar File explorer and things:
# --------------------------------
v = command(sudo -u dex -H DISPLAY=:0 XAUTHORITY=/home/dex/.Xauthority dbus-launch thunar --name=floating_thunar /home/dex/Videos &)
t = command(sudo -u dex -H DISPLAY=:0 XAUTHORITY=/home/dex/.Xauthority dbus-launch thunar --name=floating_thunar trash:/// &)
p = command(sudo -u dex -H DISPLAY=:0 XAUTHORITY=/home/dex/.Xauthority dbus-launch thunar --name=floating_thunar /home/dex/Pictures &)
a = command(sudo -u dex -H DISPLAY=:0 XAUTHORITY=/home/dex/.Xauthority dbus-launch thunar --name=floating_thunar /home/dex/Audio &)
r = command(sudo -u dex -H DISPLAY=:0 XAUTHORITY=/home/dex/.Xauthority dbus-launch thunar --name=floating_thunar recent:/// &)
d = C-A-f24


[rightalt_shift]

# leftshift = overloadt(compose_alt, oneshot(fake_alt_2), 180)
# rightshift = overloadt(compose_alt, oneshot(fake_alt_2), 180)
# rightshift = overloadt(compose_alt, oneshot(fake_alt_2), 180)

escape = S-escape
compose = S-escape
tab = S-tab
# leftshift = overloadt(coding_rightalt, oneshot(coding_rightalt), 180)
# rightshift = overloadt(coding_rightalt, oneshot(coding_rightalt), 180)
capslock = overloadt(s-tier_caps, oneshot(clone_control), 180)
space = overloadt(coding_rightalt, space, 180)



q = Q
w = W
e = E
r = R
t = T
y = Y
u = U
i = I
o = O
p = P

[ = {
] = }

a = A
s = S
d = D
f = F
g = G
h = H
j = J
k = K
l = L

; = :
' = "
\ = |

z = Z
x = X
c = C
v = V
b = B
n = N
m = M

, = <
. = >
/ = ?

` = ~
1 = !
2 = @
3 = #
4 = $
5 = %
6 = ^
7 = &
8 = *
9 = (
0 = )
- = _
= = +


f11 = S-f11

