matches:

  ##################### Esentials ###############################333

  # old ;;timer; used to look like this
  # - trigger: ";;timer;"
  #   replace: "echo \"\\n [$|$] \\n\" ; timer"


  - trigger: ";;p;"
    replace: "ignore everything else. Do not be poetic I hate poetry Be logical. Understanding first. Be brief. Use few words. Keep meaning big. Word count as low as possible. Technicality only when it matters. Concept understanding first. If you don't understand what the user wants or needs ask the user questions instead of answering for clarifications if the user is vague or broad. Please Behave and trust the user more."


  - trigger: ";;timer;"
    replace: "echo $|$; timer"

  # very useful when asking and answering questions to llm
  - trigger: ";;q;"
    force_mode: clipboard
    vars:
      - name: clip
        type: clipboard
    replace: |
      questions:
      {{clip}}
      answer:

  - trigger: ";;qq;"
    force_mode: clipboard
    vars:
      - name: clip
        type: clipboard
    replace: |
      questions:
      $|$
      answer:

  - trigger: ";;todo;"
    replace: "- [ ] "

  ################ Coding blocks #######################
  - trigger: ";;`bash;"
    replace: "```bash\n$|$\n```"
    propagate_case: false

  - trigger: ";;`py;"
    replace: "```py\n$|$\n```"
    propagate_case: false

  - trigger: ";;`c;"
    replace: "```c\n$|$\n```"
    propagate_case: false

  - trigger: ";;`scm;"
    replace: "```c\n$|$\n```"
    propagate_case: false

  - trigger: ";;`elisp;"
    replace: "```c\n$|$\n```"
    propagate_case: false

  - trigger: ";;`lua;"
    replace: "```lua\n$|$\n```"
    propagate_case: false

  - trigger: ";;`;"
    replace: "```\n$|$\n```"
    propagate_case: false



  ################ Coding blocks with clipboard content inside #######################
  - trigger: ";;cb;"
    replace: "```\n{{content}}\n```\n\n"
    force_clipboard: true
    paste_shortcut: "Ctrl+V"
    vars:
      - name: content
        type: shell
        params:
          cmd: "bash ~/scripts/espanso/paste-wrapped.sh"

  - trigger: ";;luacb;"
    replace: "```lua\n{{content}}\n```\n\n"
    force_clipboard: true
    paste_shortcut: "Ctrl+V"
    vars:
      - name: content
        type: shell
        params:
          cmd: "bash ~/scripts/espanso/paste-wrapped.sh"


  - trigger: ";;ccb;"
    replace: "```c\n{{content}}\n```\n\n"
    force_clipboard: true
    paste_shortcut: "Ctrl+V"
    vars:
      - name: content
        type: shell
        params:
          cmd: "bash ~/scripts/espanso/paste-wrapped.sh"

  - trigger: ";;pythoncb;"
    replace: "```python\n{{content}}\n```\n\n"
    force_clipboard: true
    paste_shortcut: "Ctrl+V"
    vars:
      - name: content
        type: shell
        params:
          cmd: "bash ~/scripts/espanso/paste-wrapped.sh"

  - trigger: ";;bcb;"
    replace: "```bash\n{{content}}\n```\n\n"
    force_clipboard: true
    paste_shortcut: "Ctrl+V"
    vars:
      - name: content
        type: shell
        params:
          cmd: "bash ~/scripts/espanso/paste-wrapped.sh"

  - trigger: ";;bashcb;"
    replace: "```bash\n{{content}}\n```\n\n"
    force_clipboard: true
    paste_shortcut: "Ctrl+V"
    vars:
      - name: content
        type: shell
        params:
          cmd: "bash ~/scripts/espanso/paste-wrapped.sh"

  - trigger: ";;pycb;"
    replace: "```py\n{{content}}\n```\n\n"
    force_clipboard: true
    paste_shortcut: "Ctrl+V"
    vars:
      - name: content
        type: shell
        params:
          cmd: "bash ~/scripts/espanso/paste-wrapped.sh"


  ############### Email section ##############################

  - trigger: ';;g.d;'
    replace: 'ttdextester@gmail.com'
  - trigger: ';;g.o;'
    replace: 'ossqirat@gmail.com'
  - trigger: ';;g.f;'
    replace: 'fagottarik@gmail.com'


  ############### Dev console when using youtube, hit f12 and type to make player faster or slower ############################

  - trigger: ";;yt5;"
    replace: "document.querySelector('video').currentTime += 5;"

  - trigger: ";;yt-5;"
    replace: "document.querySelector('video').currentTime -= 5;"

  - trigger: ";;yt4;"
    replace: "document.querySelector('video').currentTime += 4;"

  - trigger: ";;yt-4;"
    replace: "document.querySelector('video').currentTime -= 4;"

  - trigger: ";;yt3;"
    replace: "document.querySelector('video').currentTime += 3;"

  - trigger: ";;yt-3;"
    replace: "document.querySelector('video').currentTime -= 3;"

  - trigger: ";;yt2;"
    replace: "document.querySelector('video').currentTime += 2;"

  - trigger: ";;yt-2;"
    replace: "document.querySelector('video').currentTime -= 2;"

  - trigger: ";;yt2.5;"
    replace: "document.querySelector('video').currentTime += 2.5;"

  - trigger: ";;yt-2.5;"
    replace: "document.querySelector('video').currentTime -= 2.5;"

  - trigger: ";;yt1;"
    replace: "document.querySelector('video').currentTime += 1.04;"

  - trigger: ";;yt-1;"
    replace: "document.querySelector('video').currentTime -= 1.04;"
