#!/bin/sh

# Recreate Graphical Context
export DISPLAY=:0
export XAUTHORITY='/home/dex/.Xauthority'
export DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus'
export XDG_RUNTIME_DIR='/run/user/1000'
export XDG_SESSION_ID='1'
export XDG_SESSION_TYPE='x11'
export XDG_CURRENT_DESKTOP='i3'
export XDG_SESSION_DESKTOP='i3'
export XDG_SEAT='seat0'
export XDG_SESSION_CLASS='user'

# Theme & Path
export QT_QPA_PLATFORMTHEME='qt6ct'
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin"

# Load User Env
[ -f "$HOME/.zshenv" ] && . "$HOME/.zshenv"

exec "$@"
