#!/bin/bash

echo "--- Starting ---"


# IDEA:
# Is to always start clean every time I run this script. But I guess I can do it manually
#
# Define the COMPLETE list of sessions to manage:
# SESSIONS=("999" "config" "session" "btop" "jobs" "sync" "duck")

# Restarting sessions from 0:
# echo "--- Starting Cleanup ---"
# for SESS in "${SESSIONS[@]}"; do
#     if tmux has-session -t "$SESS" 2>/dev/null; then
#         tmux kill-session -t "$SESS"
#     fi
# done

# tmux new-session -d -s "main" -c "$HOME" -n "zsh"



tmux new-session -d -s "word" -c "$HOME" -n "d"
tmux send-keys -t "word:d" "d "

tmux new-window -t "word:2" -c "$HOME" -n "ai-d"

# tmux new-session -d -s "wiki" -c "$HOME/wiki/" -n "zsh"

# tmux new-session -d -s "config"

####
#### .learn
####

# Create session "learn" and name window 1 "main"

tmux new-session -d -s "learn" -c "$HOME/learn" -n "main"
tmux send-keys -t "learn:main" "nvim aha.md" C-m

# Window 2
tmux new-window -t "learn:2" -c "$HOME/learn/buffer" -n "duck"
tmux send-keys -t "learn:duck" "nvim duck.md" C-m

# Window 3
tmux new-window -t "learn:3" -c "$HOME/wiki/" -n "wiki"

# Focus window 1
tmux select-window -t "learn:main"





####
#### .session
####

SESS="session"
WDIR="/home/dex/learn"

SESS="session"
WDIR="/home/dex/learn"

# Window 1: session (3 panes)
tmux new-session -d -s "$SESS" -n "session"
# I don't think you need this
# tmux split-window -v -t "$SESS":1.1     # Splits 2.1 into 2.1 (top) and 2.2 (bottom)
tmux split-window -h -t "$SESS":1.1     # Splits 2.1 into 2.1 (top) and 2.2 (bottom)
# I don't think you need this you just timew whenever and things like that this way you can run it everywhere
# but to be clean we are going to keep it in workspace 10
tmux send-keys -t "$SESS":1.1 'watch -n 1 -c "timew"' C-m
tmux send-keys -t "$SESS":1.3 '10min'

# tmux new-window -t "$SESS":2 -n "timer"
# tmux send-keys -t "$SESS":2.1 "notify-timer 1h"

# Window 2: clock (3 panes - split top, full bottom)
tmux new-window -t "$SESS":2 -n "clock"
tmux split-window -h -t "$SESS":2.1     # Splits 2.1 into 2.1 (top) and 2.2 (bottom)
tmux split-window -v -t "$SESS":2.2     # Splits 2.1 into 2.1 (top-left) and 2.3 (top-right)
tmux send-keys -t "$SESS":2.1 "aclock" C-m
tmux send-keys -t "$SESS":2.2 "acal" C-m
tmux send-keys -t "$SESS":2.3 "watch -n 10 woke-up n" C-m


tmux select-window -t "$SESS":1


####
#### .btop
####

tmux new-session -d -s "btop" -n "btop" -c "$HOME"

# Window 1:
# Split 1.1 to create 1.2. -b puts new pane (1.1) on left.
# Window 1:
# Split 1.1 to create 1.2 on the RIGHT.
# -l 40 makes the right pane (ping) 40 columns wide.
tmux split-window -h -t "btop":1.1 -l 1

# Window 2
tmux new-window -t "btop":2 -c "$HOME" -n "nethogs"

# Window 3
tmux new-window -t "btop":3 -c "$HOME" -n "cpupower"
tmux split-window -h -t "btop":3.1   # Creates 3.2
tmux split-window -v -t "btop":3.2   # Creates 3.3

# Commands
tmux send-keys -t "btop":1.1 "btop" C-m
tmux send-keys -t "btop":1.2 "ping 8.8.8.8" C-m

tmux send-keys -t "btop":2.1 "sudo nethogs" C-m

tmux send-keys -t "btop":3.1 "watch -n 5 cpupower frequency-info" C-m
tmux send-keys -t "btop":3.2 "sudo cpupower frequency-set -u 2800MHz"
tmux send-keys -t "btop":3.3 "sudo cpupower frequency-set -g performance"

tmux select-pane -t "btop":1.1


####
#### .jobs
####

# tmux new-session -d -s "jobs" -n "logs"
# tmux send-keys -t "jobs:logs" "journalctl -f" C-m

####
#### .sync
####

# tmux new-session -d -s "sync" -n "dev" -c "$HOME/dev"
# tmux send-keys -t "sync":1 "sleep 1m ; git status" C-m
#
# tmux new-window -t "sync":2 -n "learn" -c "$HOME/learn"
# tmux send-keys -t "sync":2 "sleep 2m ; git status" C-m
#
# tmux new-window -t "sync":3 -n "wiki" -c "$HOME/wiki"
# tmux send-keys -t "sync":3 "sleep 3m ; git status" C-m
#
# tmux new-window -t "sync":4 -n "archive_fossil" -c "$HOME/archive_fossil/"
# tmux send-keys -t "sync":3 "sleep 3m ; git status" C-m

echo "--- Session Creation Complete ---"
