#!/bin/bash

echo "--- Starting ---"

# IDEA:
# Is to always start clean every time I run this script. But I guess I can do it manually
#
# Define the COMPLETE list of sessions to manage:
# SESSIONS=("999" "config" "session" "btop" "jobs" "sync" "duck")

# Restarting sessions from 0:
# echo "--- Starting Cleanup ---"
# for SESS in "${SESSIONS[@]}"; do
#     if tmux has-session -t "$SESS" 2>/dev/null; then
#         tmux kill-session -t "$SESS"
#     fi
# done

tmux new-session -d -s "999" -c "$HOME" -n "zsh"

tmux new-session -d -s "config"

####
#### .duck
####

tmux new-session -d -s "duck" -c "$HOME/work" -n "duck"
tmux send-keys -t "duck":1 "nvim aha.md" C-m
tmux new-window -t "duck":2 -c "$HOME/wiki" -n "wiki"
tmux send-keys -t "duck":2 "nvim questions.md" C-m

# TODO:
# I think session should be like this:
# the sessions: https://i.imgur.com/jFl4mYR.png
# window 1: https://i.imgur.com/QqAWvIU.png
# window 2: https://i.imgur.com/QPUMzkI.png
# window 3: https://i.imgur.com/xRJtfpZ.png
# window 4: https://i.imgur.com/TnDak4a.png
# window 5: https://i.imgur.com/geIH4TR.png
# window 6: https://i.imgur.com/HqVM12A.png
# ....So add the code here to auto run it like the pictures.
#

####
#### .session
####

SESS="session"
WDIR="/home/dex/work"

# Window 1: session (3 panes)
tmux new-session -d -s "$SESS" -n "session"
tmux split-window -v -t "$SESS":1
tmux select-pane -t "$SESS":1.0
tmux split-window -h -t "$SESS":1.0
tmux send-keys -t "$SESS":1.0 '(echo "running" && ssleep 1h && dunstify -u critical -t 0 "Timer" "1 hour passed" && echo "done")' C-m
tmux send-keys -t "$SESS":1.1 "timer" C-m
tmux send-keys -t "$SESS":1.2 'echo -e "\n[ [ON] [session just woke up] ]\n" ; timer' C-m

# Window 2: clock (2 panes)
tmux new-window -t "$SESS":2 -n "clock"
tmux split-window -h -t "$SESS":2
tmux send-keys -t "$SESS":2.0 "aclock" C-m
tmux send-keys -t "$SESS":2.1 "oo; d; cal; ww" C-m

# Window 3: taskwarrior (4 panes)
tmux new-window -t "$SESS":3 -n "taskwarrior"
tmux split-window -v -t "$SESS":3
tmux select-pane -t "$SESS":3.0
tmux split-window -h -t "$SESS":3.0
tmux split-window -h -t "$SESS":3.1
tmux send-keys -t "$SESS":3.0 "t" C-m
tmux send-keys -t "$SESS":3.1 "t start 1" C-m
tmux send-keys -t "$SESS":3.2 "t start 1" C-m
tmux send-keys -t "$SESS":3.3 'watch -n 3 -c "task rc._forcecolor:on"' C-m

# Window 4: timewarrior (3 panes)
tmux new-window -t "$SESS":4 -n "timewarrior"
tmux split-window -v -t "$SESS":4
tmux select-pane -t "$SESS":4.0
tmux split-window -h -t "$SESS":4.0
tmux send-keys -t "$SESS":4.0 "watch -n 3 -c timew" C-m
tmux send-keys -t "$SESS":4.1 "tt s" C-m
tmux send-keys -t "$SESS":4.2 "watch -n 3 -c timew summary" C-m

# Window 5: tasks
tmux new-window -t "$SESS":5 -n "tasks" -c "$WDIR"
tmux send-keys -t "$SESS":5 "vim tasks.md" C-m

# Window 6: sessions
tmux new-window -t "$SESS":6 -n "sessions" -c "$WDIR"
tmux send-keys -t "$SESS":6 "vim sessions.md" C-m

tmux select-window -t "$SESS":1


####
#### .btop
####

tmux new-session -d -s "btop" -n "btop" -c "$HOME"

# Window 1: Absolute minimum sidebars
# Left pane (sensors) = 5 chars
tmux split-window -h -t "btop":1.1 -l 4 -b
# Right pane (ping) = 5 chars
tmux split-window -h -t "btop":1.2 -l 1

# Window 2
tmux new-window -t "btop":2 -c "$HOME" -n "nethogs"

# Window 3
tmux new-window -t "btop":3 -c "$HOME" -n "cpupower"
tmux split-window -h -t "btop":3.1
tmux split-window -v -t "btop":3.1

# Commands
tmux send-keys -t "btop":1.1 "watch -t sensors"
tmux send-keys -t "btop":1.2 "btop" C-m
tmux send-keys -t "btop":1.3 "ping 8.8.8.8" C-m

tmux send-keys -t "btop":2.1 "nethogs" C-m

tmux send-keys -t "btop":3.1 "watch -n 5 cpupower frequency-info" C-m
tmux send-keys -t "btop":3.2 "sudo cpupower frequency-set -u 2800MHz"
tmux send-keys -t "btop":3.3 "sudo cpupower frequency-set -g performance"

tmux select-pane -t "btop":1.2

####
#### .jobs
####

tmux new-session -d -s "jobs" -n "logs"
tmux send-keys -t "jobs:logs" "journalctl -f" C-m

####
#### .sync
####

tmux new-session -d -s "sync" -n "dev" -c "$HOME/dev"
tmux send-keys -t "sync":1 "sleep 1m ; git status" C-m

tmux new-window -t "sync":2 -n "work" -c "$HOME/work"
tmux send-keys -t "sync":2 "sleep 2m ; git status" C-m

tmux new-window -t "sync":3 -n "wiki" -c "$HOME/wiki"
tmux send-keys -t "sync":3 "sleep 3m ; git status" C-m

tmux new-window -t "sync":4 -n "archive_fossil" -c "$HOME/archive_fossil/"
tmux send-keys -t "sync":3 "sleep 3m ; git status" C-m

echo "--- Session Creation Complete ---"
